### ISSUE TITLE
Centos7: list index out of range

### ISSUE THREAD

**Issue by blaisep** [mrlesmithjr/ansible-kvm#26]
Hi @mrlesmithjr , I just got this on a freshly-installed Centos7  (no virtual envs) Python 2.7.5
Should I install python3 ? Thanks, sorry to bother you on a Sunday.

```
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

When I ran the `ansible-galaxy install -r requirements.yml`

```
ansible-galaxy 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bpabon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
Opened /home/bpabon/.ansible_galaxy
found role {'scm': 'git', 'src': 'https://github.com/mrlesmithjr/ansible-config-interfaces.git', 'version': '', 'name': 'ansible-config-interfaces'} in yaml file
Processing role ansible-config-interfaces
- extracting ansible-config-interfaces to /etc/ansible/roles/ansible-config-interfaces
- extracting ansible-config-interfaces to /usr/share/ansible/roles/ansible-config-interfaces
ERROR! Unexpected Exception, this is probably a bug: list index out of range
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 150, in run
    self.execute()
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 393, in execute_install
    installed = role.install()
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/role.py", line 332, in install
    self.path = self.paths[nextidx]
IndexError: list index out of range
```

**Comment by blaisep** [comment]
OK, it seem to work when I use python3.6.3 from SCL
(...and I run it inside a pipenv, setting the `ansible_python_interpreter` in /etc/ansible/hosts)
```
Python 3.6.3 (default, Mar 20 2018, 13:50:41)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
I decided to upgrade to fc29 for other reasons, so this might be helpful for someone else.
